"use client";

import { Almarai, Cairo } from "next/font/google"; // Import both fonts
import "./globals.css";
import Navbar from "./components/BavBar/Navbar";
// import Footer from "../../components/Footer/Footer.jsx";
import { usePathname } from "next/navigation"; // Import usePathname

// Font configuration for Almarai and Cairo
const almarai = Almarai({
    weight: "400",
    subsets: ["arabic"], // Correct subset for Almarai
});

const cairo = Cairo({
    weight: ["400", "700"], // You can specify multiple weights if needed
    subsets: ["arabic"], // Correct subset for Cairo
});

export default function RootLayout({ children }) {
    const pathname = usePathname(); // Client-side hook to get current route

    // List of paths where the layout should be hidden
    const hideLayoutPaths = [
        "/registrationForms",
        "/reset-password/validate",
        "/authentication",
        "/activate",
    ];

    // Check if the current path matches any in the hideLayoutPaths array
    const hideLayout = hideLayoutPaths.some((path) => pathname.startsWith(path));

    return (
        <html lang="en" >
        <head>
            {/*<title>Manfaa</title>*/}
            <meta name="description" content="Generated by create next app"/>
            <link
                rel="stylesheet"
                href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
            />
        </head>
        <body className={`${almarai.className} ${cairo.className}`}> {/* Apply both fonts */}
        <Navbar/>
        <div>{children}</div>
      {/*<Footer />*/}
        </body>
        </html>
    );
}
